services:

    shopware:
      # use either tag "latest" or any other version like "6.5.3.0", ...
      image: dockware/dev:latest
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "8080:8080"
         - "9003:9003"
      volumes:
         - "db_volume:/var/lib/mysql"
         - "./src:/var/www/html"
      networks:
         - web
      environment:
         # default = latest PHP, optional = specific version
         - PHP_VERSION=8.3
         - HOST=0.0.0.0
         - XDEBUG_ENABLED=1
         - XDEBUG_MODE=debug
         - XDEBUG_START_WITH_REQUEST=yes
         - XDEBUG_CLIENT_HOST=host.docker.internal
         - XDEBUG_CLIENT_PORT=9003

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false